app:
  name: myapp
  version: "1.0"
  features:
    - login
    - signup
    - dashboard
  database:
    host: localhost
    port: 5432
    users:
      - name: admin
        role: superuser
      - name: guest
        role: readonly
