version: "3.9"

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - frontend

  redis:
    image: redis:7-alpine
    networks:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=<user>
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=demo
    networks:
      - backend

networks:
  frontend:
  backend:
