name: Update DevOps Timeline

on:
  push:
    branches:
      - main

jobs:
  update-timeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
    - name: Generate Timeline
      run: bash update_timeline.sh
    - name: Commit changes
      run: |
        git add README.md
        git commit -m "chore: update DevOps timeline [skip ci]" || echo "No changes"
        git push
